zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka1:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_CREATE_TOPICS: "test-messages:5:3"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
kafka2:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9093:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_CREATE_TOPICS: "test-messages:5:3"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
kafka3:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9094:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_CREATE_TOPICS: "test-messages:5:3"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
